<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.tubs.wire</groupId>
        <artifactId>rcsim-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>rcsim-demo-jfx</artifactId>
    <name>RCSim Demo JavaFX</name>

    <dependencies>
        <dependency>
            <groupId>de.tubs.wire</groupId>
            <artifactId>rcsim-simulator</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>de.tubs.wire</groupId>
            <artifactId>rcsim-graphics-support</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-math3</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-graphics</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>de.tubs.wire.rcdemo.RCJavaFX</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
