<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.tubs.wire</groupId>
        <artifactId>rcsim-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>rcsim-demo-swing</artifactId>
    <name>RCSim Demo Swing</name>

    <properties>
        <exec.mainClass>RCSwing</exec.mainClass>
    </properties>

    <dependencies>
        <dependency>
            <groupId>de.tubs.wire</groupId>
            <artifactId>rcsim-simulator</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>de.tubs.wire</groupId>
            <artifactId>rcsim-graphics-support</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>de.tubs.wire</groupId>
            <artifactId>rcsim-demo-j3d</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-math3</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jogamp.java3d</groupId>
            <artifactId>java3d-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jogamp.java3d</groupId>
            <artifactId>java3d-utils</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jogamp.java3d</groupId>
            <artifactId>vecmath</artifactId>
        </dependency>
        <!-- JOGL native libraries -->
        <dependency>
            <groupId>org.jogamp.gluegen</groupId>
            <artifactId>gluegen-rt</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jogamp.jogl</groupId>
            <artifactId>jogl-all</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jogamp.gluegen</groupId>
            <artifactId>gluegen-rt</artifactId>
            <classifier>natives-linux-amd64</classifier>
        </dependency>
        <dependency>
            <groupId>org.jogamp.jogl</groupId>
            <artifactId>jogl-all</artifactId>
            <classifier>natives-linux-amd64</classifier>
        </dependency>
    </dependencies>

</project>
